services:
  mariadb:
    image: mariadb:11.8.6
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./config/mariadb/init.sql:/docker-entrypoint-initdb.d/10-init.sql:ro
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-uroot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:3316:3306"

  redis:
    image: redis/redis-stack-server:7.4.0-v8
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:6389:6379"
